palantir/pkg

matcher/matchers.go, matcher/matchers_test.go
Provides ability to create matcher that matches on exact paths
(no glob matching).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/17)
=> Add PathLiteral matcher

safejson/gocd_imports.json, safejson/yaml.go, safejson/yaml_test.go
* Rename to safejson.FromYAMLValue to make it clear that the input
is a YAML value rather than the YAML itself
* Improve function documentation
* Add test to verify that function does not handle the case of
maps in struct fields
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/38)
=> Improve safejson.FromYAML function

pkgpath/packages.go
Fixes issue where "PackagesInDir" would fail if the executing
user could not read a file or directory in the provided rootDir,
even if the file or directory was excluded by the exclude matcher.
Cannot add test because there is no way to reliably simulate an
unreadable file/directory in a test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/46)
=> Make PackagesInDir ignore errors on excluded paths

safejson/gocd_imports.json, safejson/marshal.go, safejson/marshal_test.go
transform.Rules.Apply does not properly convert *big.Float to
json.Number: it has always returned a *big.Float. We should stop
applying this no-op transformation, because it is exorbitantly costly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/49)
=> Do not transform big.Float while encoding json for perf reasons

cli/help.go
'--help' should only reference subcommands if there is at least
one non-hidden subcommand.
Fixes #53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/54)
=> Fix '--help' subcommand bug

tableprinter/tableprinter.go, tableprinter/tableprinter_test.go
Differences from internal version:
* Use built-in errors instead of stacktrace
* Add "includeHeaderSeparator" functionality which allows '-' to
be printed as a separator under headers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/56)
=> Add tableprinter

cli/app.go, cli/cliviper/cliviper.go, cli/cliviper/cliviper_test.go, cli/gocd_imports.json, cli/run.go
Allows CLI applications to be configured such that actions
automatically bind their flag values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/61)
=> Add ContextOptions and add viper implementation

cli/flag/duration_flag.go
I think this was just an accidental omission, but I just ran into a use case where I wanted it.
@nmiyake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/69)
=> cli: Add EnvVar for DurationFlag

cli/app.go, cli/context.go, cli/parse.go, cli/run.go, cli/run_test.go
The basic motivation behind this PR is to add the ability to configure a custom `context.Context` on `cli.App` **once** (such as a complex service logger), and consume that context from anywhere in the cli. Specifically:
- Off of the `cli.App` itself
- Inside of `cli.App.ErrorHandler`
- Inside of `cli.App.Command.Action`
- Inside of `cli.App.Command.Subcommands`
I am aiming for the guarantee that if an app is created normally via `cli.NewApp()`, then a valid (non-`nil`) context is provided in all cases outlined above.
Hopefully this help reduce code duplication in consumer applications, and enable a more straight-forward approach with custom application logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Pass a configurable context.Context along with cli.Context

cobracli/execute.go
Ensure that the command that is executed is the command that is
provided to the handler (previously, root command was always
provided).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/81)
=> Fix command provided to error handler

cobracli/default.go, cobracli/default_test.go, cobracli/execute.go
Add an error handler decorator that prints the usage for a command
if it fails due to a required flag not being specified and use the
handler in the default executor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/82)
=> Add required flag error handler to default runner

cobracli/default.go, cobracli/default_test.go
Update "ExecuteWithDefaultParams" function to use the new default
version variable and add a new "ExecuteWithDefaultParamsWithVersion"
function that allows version variable to be specified explicitly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/83)
=> Add default version variable

matcher/matchers.go, matcher/matchers_test.go
Update name matcher to ignore ".." path components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/88)
=> matcher: fix handling of parent directories ("..")

metrics/registry.go, metrics/registry_test.go
Adding metrics that we know are never actually read, even though they are emitted
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/114)
=> Remove unused metrics from the metrics pkg

metrics/registry.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/124)
=> metrics: Add CaptureRuntimeMemStatsWithCancel function

retry/retry.go, retry/retry_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/127)
=> Add retry package

bytesbuffers/pool.go, bytesbuffers/pool_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/128)
=> Add bytesbuffers package

signals/signals.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/129)
=> Add signals.RegisterStackTraceHandlerOnSignals for custom handling logic

metrics/benchmark_test.go, metrics/registry.go, metrics/tag.go
`toMetricTagsID` is called every time a metric is incremented/changed. This PR updates the implementation to run faster and allocate less memory.
Benchmark results:
Old
```
goos: darwin
goarch: amd64
pkg: github.com/palantir/pkg/metrics
BenchmarkRegisterMetric/1_tag-8          2000000     908 ns/op     800 B/op   10 allocs/op
BenchmarkRegisterMetric/10_tag-8          300000    4905 ns/op    2910 B/op   27 allocs/op
BenchmarkRegisterMetric/100_tag-8          30000   53716 ns/op   30639 B/op  136 allocs/op
PASS
ok  	github.com/palantir/pkg/metrics	6.802s
```
New
```
goos: darwin
goarch: amd64
pkg: github.com/palantir/pkg/metrics
BenchmarkRegisterMetric/1_tag-8          5000000     300 ns/op     208 B/op    4 allocs/op
BenchmarkRegisterMetric/10_tag-8         2000000     657 ns/op     368 …
```
=> 🚀 Speed up toMetricTagsID

rid/resource_identifier.go, rid/resource_identifier_test.go
- Add rid constructors for when you know the pieces of the identifier 
- Add additional tests (caught no incorrect functionality 👍  )
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/134)
=> Add rid constructors

rid/resource_identifier.go
- Don't export rid constants
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/135)
=> Don't export rid constants 

binary/binary.go, binary/binary_test.go
The conjure wire specification requires binary data to be encoded in base64 when serialized as a string. This helper type facilitates this encoding when used as a struct/map/slice member.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/137)
=> Add binary package for base64 encoding

safeyaml/jsontoyaml.go, safeyaml/jsontoyaml_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/139)
=> Adds safeyaml.JSONtoYAML for safer marshaling

godel/config/check-plugin.yml, safeyaml/ghodss_yaml.go, safeyaml/yamltojson.go, safeyaml/yamltojson_test.go
Reverse of #139
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/141)
=> Add safeyaml.YAMLUnmarshalerToJSONBytes

metrics/registry.go, metrics/registry_test.go
Fixes a bug introduced in #130 where the `tags` slice can be mutated by `sort.Sort`, affecting caller code unexpectedly.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/143)
=> metrics: copy tags list before serializing

metrics/registry.go, metrics/registry_internal_test.go
We were leaking memory by failing to clean up metricIds from our internal map. This adds that cleanup while preserving correctness guarantees in `Each()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/145)
=> Fix memory leak in Unregister

metrics/tag.go
We frequently want to create a tag with a known key, but potentially invalid value, in which case we want to fall back to a known value such as the string `unknown`. This allows us to do so without repeatedly rewriting the same fallback code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/152)
=> Metrics: creating tags with fallback value

metrics/context.go, metrics/context_test.go
Fixes #151
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/153)
=> metrics.AddTags should not mutate the input context

go.mod
Now that all packages are modules, create a top-level module
definition. This is required to prevent ambiguous import paths
when switching consumption to modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/181)
=> Create top-level module

main.go
Allows the github.com/palantir/pkg module to be declared as a
module dependency, which can be used to resolve duplicate import
path issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/182)
=> Add top-level main.go file

retry/retry.go, retry/retry_test.go
A not uncommon pattern is to use an initial backoff that is larger than the default max backoff. For example:
```
err = retry.Do(ctx, func() error {
// do things
}, retry.WithMaxAttempts(5), retry.WithInitialBackoff(15*time.Second), retry.WithMultiplier(1))
```
I'd expect this to retry 5 times, every 15 seconds. However, because the default backoff is 2s, we end up retrying every two seconds.
The proposed change is to use the larger of max backoff or initial backoff in situations where the current backoff is larger than the max backoff.
Explicitly setting your initial backoff larger than your max backoff is nonsensical anyways, so I haven't been able to come up with an example where this change is detrimental.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Change backoff semantics in case of initialBackoff

retry/retry.go, retry/retry_test.go
When adding functionality to override the max backoff, we need to special case when no backoff is set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/189)
=> stop overriding max backoff when none is set

tlsconfig/common.go, tlsconfig/tlsconfig_client.go, tlsconfig/tlsconfig_client_test.go, tlsconfig/tlsconfig_server.go, tlsconfig/tlsconfig_server_test.go, tlsconfig/tlsconfig_test.go
Golang TLS supports `GetClientCertificate` in tls config, which calls a function when a certificate is requested instead of serving a static certificate. We change the `ClientKeyPair` param to use this field instead of setting a static certificate. `ClientKeyPairFiles` remains static. This enables users to refresh their certificates so they don't expire.
Comments have been updated to clarify the differences between params.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/194)
=> Fix ClientKeyPair param in tlsconfig so clients refresh by default

tlsconfig/tlsconfig_client.go, tlsconfig/tlsconfig_client_test.go
It is currently not possible to use the tlsconfig package without requiring secure TLS. Surfacing this option enables rare but necessary off-roading.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/203)
=> Make tls.InsecureSkipVerify configurable.

metrics/registry.go
```
// new
BenchmarkRegisterMetric
BenchmarkRegisterMetric/1_tag
BenchmarkRegisterMetric/1_tag-16         	 4665692	       239.6 ns/op	      96 B/op	       3 allocs/op
BenchmarkRegisterMetric/10_tag
BenchmarkRegisterMetric/10_tag-16        	 2098387	       573.9 ns/op	     616 B/op	       3 allocs/op
BenchmarkRegisterMetric/100_tag
BenchmarkRegisterMetric/100_tag-16       	  106561	     11235 ns/op	    6168 B/op	       3 allocs/op
// old
BenchmarkRegisterMetric
BenchmarkRegisterMetric/1_tag
BenchmarkRegisterMetric/1_tag-16         	 3992419	       276.9 ns/op	     120 B/op	       4 allocs/op
BenchmarkRegisterMetric/10_tag
BenchmarkRegisterMetric/10_tag-16        	 1766430	       668.3 ns/op	     728 B/op	       4 allocs/op
BenchmarkRegisterMetric/100_tag
BenchmarkRegisterMetric/100_tag-16 …
```
=> metrics: Use strings.Builder in toMetricTagsID

metrics/benchmark_test.go, metrics/registry.go
Currently, calling registry.Histogram(...) allocates a DefaultSample() on every call. The underlying gometrics library supports lazy instantiation on the histogram itself (which is used in GetOrRegisterHistogram) but not the Sample.
This PR updates our implementation to use GetOrRegister directly, deferring sample creation to when the registry decides to allocate a new metric object.
Benchmark comparison:
```
name                                              old time/op    new time/op    delta
Histogram/Histogram_with_cached_Tag-16              3.25µs ± 1%    0.73µs ± 2%  -77.42%  (p=0.000 n=11+10)
Histogram/Histogram_with_NewTag-16                  3.55µs ± 1%    1.01µs ± 2%  -71.62%  (p=0.000 n=12+10)
name                                              old alloc/op   new alloc/op   delta …
```
=> metrics: Lazily instantiate Histogram Sample

.circleci/config.yml, .circleci/generate.go
This change only updates the Go version used in CircleCI and does not touch any of the go directives in the various `go.mod` files.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/229)
=> Upgrade Go versions to 1.17.5/1.16.12

gittest/gittest.go
Currently, gittest functions in a way that inherits any values set in the system or user global git configuration. For users who have settings which force GPG signing on commits and tags, this makes running local tests impractical, as tests will fail without user actions during the test.
By ignoring any system and global settings, we'll force users to acknowledge any local configuration that is depended on and require it to be set up during the test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/297)
=> Update gittest to ignore system and global settings

metrics/registry.go, metrics/sort.go, metrics/sort_go121.go
```
pkg: github.com/palantir/pkg/metrics
│   old.txt    │               new.txt               │
│    sec/op    │   sec/op     vs base                │
RegisterMetric/1_tag-10                            119.80n ± 2%   94.67n ± 1%  -20.98% (p=0.000 n=10)
RegisterMetric/10_tag-10                            278.8n ± 0%   266.6n ± 1%   -4.36% (p=0.000 n=10)
RegisterMetric/100_tag-10                           5.065µ ± 1%   6.884µ ± 0%  +35.93% (p=0.000 n=10)
Histogram/HistogramWithSample_with_cached_Tag-10    283.9n ± 1%   261.8n ± 0%   -7.78% (p=0.000 n=10)
Histogram/Histogram_with_cached_Tag-10              269.3n ± 1%   242.7n ± 0%   -9.88% (p=0.000 n=10)
Histogram/HistogramWithSample_with_NewTag-10        394.9n ± 1%   376.5n ± 1%   -4.67% (p=0.000 n=10)
Histogram/Histogram_with_NewTag-10 …
```
=> improvement: Use go1.21's slices package to avoid allocation in sorting

metrics/benchmark_test.go, metrics/registry.go, metrics/sort_go121.go, metrics/tag.go, metrics/tag_test.go
```
pkg: github.com/palantir/pkg/metrics
│   old.txt    │              new.txt               │
│    sec/op    │   sec/op     vs base               │
NewTag/tagLen:2-10                                  59.86n ± 2%   12.11n ± 1%  -79.77% (p=0.001 n=7)
NewTag/tagLen:10-10                                 91.77n ± 1%   15.65n ± 1%  -82.95% (p=0.001 n=7)
NewTag/tagLen:100-10                               414.10n ± 1%   83.79n ± 1%  -79.77% (p=0.001 n=7)
NewTag/tagLen:199-10                                745.8n ± 2%   174.2n ± 1%  -76.64% (p=0.001 n=7)
NormalizeTag/a❌Long❌Tag❌With❌Emoji❌Chars-10    273.6n ± 3%   223.8n ± 1%  -18.20% (p=0.001 n=7)
NormalizeTag/a_Long_Tag_With_Space_Chars-10         195.3n ± 1%   145.7n ± 1%  -25.40% (p=0.001 n=7)
NormalizeTag/aLongTagValueWithUpperChars-10 …
```
=> improvement: Drop keyValue field in metrics.Tag; normalizeTag short-circuits simple strings

tlsconfig/common.go
We included the following ciphers in our set of default ciphers:
- `TLS_RSA_WITH_AES_256_GCM_SHA384`
- `TLS_RSA_WITH_AES_256_CBC_SHA`
In Go 1.22 there ciphers were marked as insecure ([commit](https://github.com/golang/go/commit/dc5a0d276bbcd6120325c9e0f9c8fd099fa2b8d6)). Trying to run a server with these ciphers can result in `unknown cipher` errors. Users can force use these ciphers via `GODEBUG` flags, but we should pre-emptively remove these ciphers as they are now considered insecure.
This PR updates the set of ciphers we use in Go to the current desirable set of cipher-suites. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/340)
=> fix: Remove ciphers considered insecure in go 1.22.

yamlpatch/types.go
Previously, operations weren't properly yaml-deserializable due to the `Type` field rename.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/341)
=> Add field tags for yaml parsing of yamlpatch.Operation

yamlpatch/container_test.go, yamlpatch/patch.go, yamlpatch/patch_test.go, yamlpatch/types.go
This PR updates the `Patch` struct to include a `Comment` field, which is piped to the `HeadComment` field in the generated `yaml.Node` for `Add` and `Replace` operations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/349)
=> Add ability to patch yaml with comments

refreshable/refreshable.go, refreshable/refreshable_default.go, refreshable/refreshable_example_test.go
- `Cached()` subscribes to an upstream refreshable and stores the result in one it creates. 
- `View()` does not create a subscription nor a cached value of the resulting type. Instead, the implementations of `Current()` and `Subscribe()` convert the upstream Refreshable's return values on every invocation. This reduces memory pressure for cheap or infrequent conversions like struct field accessors.
- `Merge()` combines two refreshables into one using a `reduceFn`. An update to either will refresh the reduced value.
- `Collect()` combines a list of refreshables of the same type into a refreshable slice type. 
This PR also adds some `Example*` tests to improve the package's godoc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> refreshables: New constructors for more flexibility in how derivative refreshables are created

metrics/benchmark_test.go, metrics/value.go, metrics/value_test.go
witchcraft-go-server is seeing a lot of allocation activity calculating metric values that are blacklisted/skipped. By deferring their computation per-key, we can avoid that wasted work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/374)
=> metrics.MetricVal: Add Keys() and Value() to reduce allocations when counting cardinality and emitting metric logs

metrics/registry.go
Allows for calling CaptureRuntimeMemStats explicitly rather than wrapping it in its own goroutine/ticker.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/373)
=> Add metrics.CaptureRuntimeMemStatsFunc()

datetime/datetime.go, safelong/safelong.go
The strings used in these implementations are allocated and immediately discarded
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/380)
=> datetime and safelong: MarshalText implementations avoid string->[]byte conversion

refreshable/v2.go, refreshable/v2_test.go
Due to the backing implementations of v1 refreshables not calling the subscription callback when the subscription is registered, there is a race condition where an update from the v1 refreshable is not propagated to the v2 refreshable if the update happens after the v2 is created and before the subscription is registered.
First commit provides failing test.
Second commit fixes it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/381)
=> 🐛 fix ToV2 missed-update race-condition
