circle.yml, cli/gocd_imports.json, godel/config/check.yml, godel/config/exclude.yml, godel/config/format.yml, godel/config/godel.properties, godel/config/imports.yml, godelw, matcher/gocd_imports.json, pkgpath/gocd_imports.json, specdir/gocd_imports.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/19)
=> Add gödel to project

signals/signals.go, signals/signals_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/21)
=> Add signals package

signals/signals.go, signals/signals_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/23)
=> Add NewSignalReceiver function

signals/signals.go, signals/signals_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/22)
=> Add error handler parameter to RegisterStackTraceWriter

godel/config/imports.yml, signals/gocd_imports.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/24)
=> Track signals package using gocd

circle.yml, cli/context_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/28)
=> Circle ci2

encryption/aes.go, encryption/aes_test.go, encryption/bytes.go, encryption/encode.go, encryption/encode_test.go, encryption/gocd_imports.json, encryption/symmetric.go, encryption/symmetric_test.go, godel/config/imports.yml, vendor/gopkg.in/yaml.v2/LICENSE, vendor/gopkg.in/yaml.v2/LICENSE.libyaml, vendor/gopkg.in/yaml.v2/README.md, vendor/gopkg.in/yaml.v2/apic.go, vendor/gopkg.in/yaml.v2/decode.go, vendor/gopkg.in/yaml.v2/emitterc.go, vendor/gopkg.in/yaml.v2/encode.go, vendor/gopkg.in/yaml.v2/parserc.go, vendor/gopkg.in/yaml.v2/readerc.go, vendor/gopkg.in/yaml.v2/resolve.go, vendor/gopkg.in/yaml.v2/scannerc.go, vendor/gopkg.in/yaml.v2/sorter.go, vendor/gopkg.in/yaml.v2/writerc.go, vendor/gopkg.in/yaml.v2/yaml.go, vendor/gopkg.in/yaml.v2/yamlh.go, vendor/gopkg.in/yaml.v2/yamlprivateh.go, vendor/vendor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/27)
=> Add encryption package

circle.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/30)
=> Fix test output location in CircleCI

circle.yml
Also run "verify" task in both environments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/31)
=> Save test output for tests run in Go 1.8 and 1.7

circle.yml
* Break out steps into more granular parts
* Factor out node-specific logic into single variable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/32)
=> Refactor circle.yml to work more naturally with parallelism

circle.yml
Makes it more clear that variable is a script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/33)
=> Rename GO_VERSION variable in circle.yml to GET_GO_VERSION

encryption/symmetric.go
Improves performance by avoiding extra allocations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/29)
=> Treat encryption key prefixes as []byte instead of string

matcher/files_test.go, pkgpath/packages_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/34)
=> Fix tests to make defer calls before checking errors

matcher/config.go, matcher/config_test.go, matcher/gocd_imports.json, pkgpath/gocd_imports.json
Adds configuration that allows matcher that includes exclude
criteria to be specified as configuration. Also adds tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/37)
=> Add NamesPathsWithExcludeCfg

encryptedconfigvalue/algorithms.go, encryption/aeskey.go, encryption/rsakey.go
Add an adapter fucntion to algorihtms to deal with this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/41)
=> Update key generation functions to returned typed keys

encryptedconfigvalue/aeskey.go, encryptedconfigvalue/gocd_imports.json, encryptedconfigvalue/rsakeys.go, encryption/aesgcmcipher.go, encryption/aeskey.go, encryption/random.go
* Export RandomBytes as a public function
* Add functions that create KeyWithType structs from keys
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/42)
=> Make improvements to the encrypted-config-value API

circle.yml
Update to fixed revision of go-1.7.5-1.8.1 image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/44)
=> Update Docker image used for CircleCI

godel/config/imports.yml, safehttp/client.go, safehttp/client_test.go, safehttp/default_client_test.go, safehttp/doc.go, safehttp/functions.go, safehttp/gocd_imports.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/43)
=> Add safehttp package

README.md, godel/config/imports.yml, objmatcher/gocd_imports.json, objmatcher/matcher.go, objmatcher/matcher_test.go
Add package that defines matchers that allow objects to be
matched.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/47)
=> Add objmatcher package

objmatcher/matcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/50)
=> Add AnyMatcher

objmatcher/matcher.go
Update error to include extra keys and missing keys rather than
just reporting that the size is different.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/51)
=> Update matcher error for maps to be more descriptive

cli/context.go, cli/context_test.go, cli/flag/int_flag.go, cli/parse_test.go
- Use subtests in parse_test.go for test case names
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/52)
=> Add IntFlag type

cli/context.go, cli/parse.go, cli/parse_test.go
* Provide a function that allows the retrieval of all values specified
for a particular string, int or duration flag
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/55)
=> Add support for getting slice of all flag values

godel/config/imports.yml, httpserver/gocd_imports.json, httpserver/httpserver.go, httpserver/httpserver_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/58)
=> Add httpserver package

circle.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/60)
=> Update Go version in circle.yml

httpserver/doc.go, httpserver/httpserver.go, httpserver/httpserver_test.go
* Add documentation
* Use parameter function paradigm to make more parameters optional,
expose more configurable parameters and provide sensible default values
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/64)
=> Update httpserver functions

godel/config/godel.properties, godelw
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/65)
=> Update gödel to 0.21.0

.circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/66)
=> Update CircleCI 2.0 config

.circleci/config.yml, godel/config/godel.properties, godelw
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/67)
=> Use CircleCI 2.0 workflows

.circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/72)
=> Remove Go 1.7 verification from CircleCI jobs

.circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/74)
=> Update CircleCI to only run tests on non-current Go version

cli/parse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/77)
=> Add safety check to ensure that context is non-nil

.circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/80)
=> Update CircleCI Go image versions

vendor/github.com/spf13/cobra/README.md, vendor/github.com/spf13/cobra/command.go, vendor/github.com/spf13/cobra/command_test.go, vendor/vendor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/84)
=> Update spf13/cobra dependency

cobracli/default.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/85)
=> Export version variable

tlsconfig/tlsconfig_server.go, tlsconfig/tlsconfig_server_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/86)
=> tlsconfig: add ability to set server's NextProtos

gittest/gittest.go, gittest/gocd_imports.json, godel/config/imports.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/89)
=> Add gittest package

gittest/gittest.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/90)
=> Update RunGitCommand to return string of output

matcher/config.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/91)
=> Update NamesPathsCfg to use omitempty annotation

matcher/config.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/92)
=> Add 'omitempty' annotations to NamesPathsWithExcludeCfg

signals/signals.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/108)
=> Add documentation for usage of signals function

metrics/registry.go, metrics/registry_test.go
First commit adds a test that consistently panics due to the Each() implementation handling concurrent Unregister calls correctly.
Second commit adds a fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/116)
=> Fix race condition in Each()

objmatcher/matcher.go, objmatcher/matcher_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/118)
=> Add SliceMatcher type to objmatcher package

metrics/context.go, metrics/context_test.go
@bmoylan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/122)
=> Return tagged metrics registry from metrics.FromContext call.

metrics/registry.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/123)
=> Deprecate Subregistry method on the RootRegistry interface.

metrics/registry.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/125)
=> Fix documentation on function

metrics/registry_test.go
Use more canonical style.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/126)
=> Touch up tests

bearertoken/bearertoken.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/136)
=> bearer token implements text (un)marshal

Gopkg.lock, Gopkg.toml, vendor/github.com/rcrowley/go-metrics/meter.go, vendor/github.com/rcrowley/go-metrics/sample.go
This adds decay to histograms on reads in addition to
updates.
Fixes #142 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/144)
=> Switch to go-metrics fork

typenames/names.go, typenames/names_test.go, typenames/specific.go
- Add typenames package for human readable names for unknown types
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/156)
=> Add typenames package

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/159)
=> Add newline to end of README.

merge/merge.go, merge/merge_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/157)
=> Add merge package for merging maps.

bearertoken/bearertoken.go
@nmiyake in case this helps with https://github.com/palantir/conjure-go/pull/70
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/164)
=> bearertoken.Token implements fmt.Stringer

binary/binary.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/165)
=> Implement String() for binary.Binary

cli/completion.go, cli/parse_test.go, godel/config/godel.properties, godelw, safehttp/client_test.go, safehttp/default_client_test.go, tlsconfig/tlsconfig_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/172)
=> Update godel to 2.17.0

metrics/microsecondstimer.go, metrics/microsecondstimer_test.go, metrics/registry.go
Fixes #173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/174)
=> Use microseconds as unit for Timer metrics

metrics/go.mod, metrics/go.sum, metrics/vendor/github.com/palantir/go-metrics/sample.go, metrics/vendor/modules.txt
Includes https://github.com/palantir/go-metrics/pull/7
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/184)
=> [fix] Upgrade palantir/go-metrics to v1.1.1

refreshable/refreshable_types.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/201)
=> refreshable: Add Map and Subscribe methods to builtins

yamlpatch/patch.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/202)
=> yamlpatch: Remove ApplyIndent

refreshable/refreshable_types.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/205)
=> refreshable: Add int64 and float64 types

refreshable/refreshable_validating.go, refreshable/refreshable_validating_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/208)
=> refreshable: fix: update non-mapping validating refreshable

refreshable/refreshable_validating.go, refreshable/refreshable_validating_test.go
Moves https://github.com/palantir/witchcraft-go-server/pull/143 and adds a test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/209)
=> refreshable: Fix race condition in NewValidatingRefreshable

.circleci/config.yml, .circleci/generate.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/240)
=> Update CircleCI base image to 1.18-browsers

.circleci/config.yml, .circleci/generate.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/275)
=> Update CircleCI base image to 1.19-browsers

uuid/uuid.go, uuid/uuid_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/285)
=> uuid: Implement BinaryMarshaler/BinaryUnmarshaler and expose FromBytes

bytesbuffers/pool.go, bytesbuffers/pool_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/286)
=> bytesbuffers: Do not reuse buffers that have grown beyond specified capacity

refreshable/go.mod, refreshable/go.sum, refreshable/v2.go, refreshable/v2_test.go, refreshable/vendor/github.com/palantir/pkg/refreshable/v2/LICENSE, refreshable/vendor/github.com/palantir/pkg/refreshable/v2/async.go, refreshable/vendor/github.com/palantir/pkg/refreshable/v2/godelw, refreshable/vendor/github.com/palantir/pkg/refreshable/v2/main.go, refreshable/vendor/github.com/palantir/pkg/refreshable/v2/refreshable.go, refreshable/vendor/github.com/palantir/pkg/refreshable/v2/refreshable_default.go, refreshable/vendor/github.com/palantir/pkg/refreshable/v2/refreshable_validating.go, refreshable/vendor/modules.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/329)
=> refreshable v1: Add ToV2() and FromV2() conversion functions

.circleci/config.yml, .circleci/generate.go, metrics/microsecondstimer_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/pkg/370)
=> Update CircleCI Go image to 1.24.1
